### ISSUE TITLE
Table for differences between instance status

### ISSUE THREAD

**Issue by chainhead** [awsdocs/amazon-ec2-user-guide#128]
Row 3, Col 3 is a copy-paste of Row 3, Col 2.

**Comment by lkdavies** [comment]
Hello, 

Thanks for your feedback on our documentation. 

Which table are you referring to? Is it this one? 
https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/ec2-instance-lifecycle.md#differences-between-reboot-stop-hibernate-and-terminate

**Comment by chainhead** [comment]
Yes.

**Comment by lkdavies** [comment]
Thank you for confirming. For "Elastic IP addresses (IPv4)", the elastic IP address does remain associated with an Amazon-EBS backed instance when it is stopped / started. So while the information in Row 3, Col 3 is identical to that in Row 3, Col 2, it is because the behavior is the same.

For reference, please see:
https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/ec2-instance-lifecycle.md#instance-stop-and-start-amazon-ebs-backed-instances-only

Thanks again for reaching out to us. I hope this information helps.
