### ISSUE TITLE
EC2 fleet allocation strategy talks about SPOT fleet allocation strategy instead

### ISSUE THREAD

**Issue by jxuamazon** [awsdocs/amazon-ec2-user-guide#275]
https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/ec2-fleet-allocation-strategy.md

This page refer to "SPOT" fleet in many places. Just a bad cut and paste ?

**Comment by mariflax** [comment]
Hi. The page refers to "Spot Instances", not "Spot Fleet". But we will review the page to see whether we should make it more inclusive of On-Demand Instances, because an EC2 Fleet (and similarly a Spot Fleet) can be configured to launch either Spot Instances or On-Demand Instances, or both. Thanks for taking the time to write to us!

Thanks,
Marilyn

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
